### ISSUE TITLE
Error installing manim-voiceover[recorder]

### ISSUE THREAD

**Issue by SSSayon** [ManimCommunity/manim-voiceover#52]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://github.com/ManimCommunity/manim-voiceover/blob/main/README.md).

## Description of error

When I followed the steps in https://voiceover.manim.community/en/latest/quickstart.html (*Record your own voiceover* Part) and run ```manim -pql my_awesome_scene.py --disable_caching``` , it told me to install ```manim-voiceover[recorder]``` first:
```
[05/15/23 18:14:21] ERROR    Missing packages. Run `pip install  __init__.py:14
                             "manim-voiceover[recorder]"` to use
                             RecorderService.
                    INFO     The extra packages required by       helper.py:165
                             RecorderService are not installed.
                             Shall I install them for you? [Y/n]
```
But when I run ```pip install "manim-voiceover[recorder]``` , it got error: (see below)

## Installation logs

<details><summary>Terminal output</summary>

```
$ pip install "manim-voiceover[recorder]"
Requirement already satisfied: manim-voiceover[recorder] in c:\users\_sayon\appdata\local\programs\python\python311\lib\site-packages (0.3.1)
Requirement already satisfied: PyAudio<0.3.0,>=0.2.12 in c:\users\_sayon\appdata\local\programs\python\python311\lib\site-packages (from manim-voiceover[recorder]) (0.2.13)
Requirement already satisfied: humanhash3<0.0.7,>=0.0.6 in c:\users\_sayon\appdata\local\programs\python\python311\lib\site-packages (from manim-voiceover[recorder]) (0.0.6)
Requirement already satisfied: manim in c:\users\_sayon\appdata\local\programs\python\python311\lib\site-packages (from manim-voiceover[recorder]) (0.17.3)
Requirement already satisfied: mutagen<2.0.0,>=1.46.0 in c:\users\_sayon\appdata\local\programs\python\python311\lib\site-packages (from manim-voiceover[recorder]) (1.46.0)
Requirement already satisfied: pip>=21.0.1 in c:\users\_sayon\appdata\local\programs\python\python311\lib\site-packages (from manim-voiceover[recorder]) (23.1.2)
Collecting playsound<2.0.0,>=1.3.0 (from manim-voiceover[recorder])
  Using cached playsound-1.3.0.tar.gz (7.7 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [29 lines of output]
  Traceback (most recent call last):
    File "C:\Users\_Sayon\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\_Sayon\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\_Sayon\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\_Sayon\AppData\Local\Temp\pip-build-env-h68he88l\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\_Sayon\AppData\Local\Temp\pip-build-env-h68he88l\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\Users\_Sayon\AppData\Local\Temp\pip-build-env-h68he88l\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\_Sayon\AppData\Local\Temp\pip-build-env-h68he88l\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 6, in <module>
    File "C:\Users\_Sayon\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 1262, in getsource
      lines, lnum = getsourcelines(object)
                    ^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\_Sayon\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 1244, in getsourcelines
      lines, lnum = findsource(object)
                    ^^^^^^^^^^^^^^^^^^
    File "C:\Users\_Sayon\AppData\Local\Programs\Python\Python311\Lib\inspect.py", line 1081, in findsource
      raise OSError('could not get source code')
  OSError: could not get source code
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

</details>

## System specifications

<details><summary>System Details</summary>

- OS (with version, e.g., Windows 10 v2004 or macOS 10.15 (Catalina)): Windows 11 22H2 22621.1702
- RAM: 16GB
- Python version (`python/py/python3 --version`): Python 3.11.2
- Installed modules (provide output from `pip list`):
```
Package                        Version
------------------------------ --------
altgraph                       0.17.3
azure-cognitiveservices-speech 1.28.0
certifi                        2023.5.7
charset-normalizer             3.1.0
click                          8.1.3
click-default-group            1.2.2
cloup                          0.13.1
colorama                       0.4.6
colour                         0.1.5
contourpy                      1.0.7
cycler                         0.11.0
decorator                      5.1.1
filelock                       3.12.0
fonttools                      4.39.3
glcontext                      2.3.7
gTTS                           2.3.2
humanhash3                     0.0.6
idna                           3.4
isosurfaces                    0.1.0
Jinja2                         3.1.2
kiwisolver                     1.4.4
manim                          0.17.3
manim-voiceover                0.3.1
ManimPango                     0.4.3
mapbox-earcut                  1.0.1
markdown-it-py                 2.2.0
MarkupSafe                     2.1.2
matplotlib                     3.7.1
mdurl                          0.1.2
moderngl                       5.8.2
moderngl-window                2.4.3
mpmath                         1.3.0
multipledispatch               0.6.0
mutagen                        1.46.0
networkx                       2.8.8
numpy                          1.24.3
packaging                      23.1
pandas                         2.0.1
pefile                         2023.2.7
Pillow                         9.5.0
pip                            23.1.2
PyAudio                        0.2.13
pycairo                        1.23.0
pydub                          0.25.1
pyglet                         2.0.7
Pygments                       2.15.1
pyinstaller                    5.10.1
pyinstaller-hooks-contrib      2023.2
pyparsing                      3.0.9
pyrr                           0.10.3
python-dateutil                2.8.2
python-dotenv                  0.21.1
pytz                           2023.3
pywin32-ctypes                 0.2.0
requests                       2.30.0
rich                           13.3.5
scipy                          1.10.1
screeninfo                     0.8.1
setuptools                     65.5.0
six                            1.16.0
skia-pathops                   0.7.4
sox                            1.4.1
srt                            3.5.3
svgelements                    1.9.4
svgwrite                       1.4.3
sympy                          1.11.1
torch                          2.0.0
tqdm                           4.65.0
typing_extensions              4.5.0
tzdata                         2023.3
urllib3                        2.0.2
watchdog                       2.3.1

```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): TeX Live 2022
+ Installed LaTeX packages: pretty much and it exceeds the word limit

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 5.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
```
</details>

**Comment by JaMeZ-B** [comment]
This might be connected to https://github.com/TaylorSMarks/playsound/issues/143

**Comment by SSSayon** [comment]
> 

Means that I need to reinstall my python/pip?

**Comment by osolmaz** [comment]
playsound has been removed as a dependency, so this error should be fixed. Let me know if pydub creates any issues
