### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'text'

### ISSUE THREAD

**Issue by mayankwebbing** [ManimCommunity/manim-voiceover#99]
## Description of bug / unexpected behavior

When working on windows the code is working fine, but during testing on ec2 aws and macbook generating several issues. `AttributeError: 'dict' object has no attribute 'text'`  or sometimes, 
```bash
ERROR    Missing packages. Run `pip install "manim-voiceover[transcribe]"` to be able to transcribe voiceovers. base.py:145
INFO     The extra packages required by SpeechService.set_transcription() are not installed. Shall I install  helper.py:165
         them for you? [Y/n] 
```
but when trying to install all dependencies at once as suggested  using `pip install --upgrade "manim-voiceover[all]"`, it generates.
```bash
spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/var/www/html/manim/ap_gp_explanation.py", line 8, in <module>
    from manim_voiceover.services.openai import OpenAIService
ModuleNotFoundError: No module named 'manim_voiceover.services.openai'
```
then again need to run `pip install --upgrade "manim-voiceover[openai]"`.

## Expected behavior

This code should create manim animation video with narations of explaining the topic of AP and GP. works on window machine and giving issue on mac or linux. Already installed all requirements from [installation page](https://voiceover.manim.community/en/latest/installation.html).

## How to reproduce the issue

<details><summary>Code for reproducing the problem</summary>

```py
import os
from manim import *
from manim_voiceover import VoiceoverScene
from manim_voiceover.services.openai import OpenAIService

class SceneWithTimings(VoiceoverScene):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.total_runtime = 0
        self.set_speech_service(
            OpenAIService(
                voice="alloy",
                model="tts-1",
            )
        )

    def play(self, *args, subcaption=None, subcaption_duration=None, subcaption_offset=0, **kwargs):
        start_time = self.renderer.time
        super().play(
            *args,
            subcaption=subcaption,
            subcaption_duration=subcaption_duration,
            subcaption_offset=subcaption_offset,
            **kwargs,
        )
        self.total_runtime += self.renderer.time - start_time

    def wait(self, duration=1, **kwargs):
        start_time = self.renderer.time
        super().wait(duration, **kwargs)
        self.total_runtime += self.renderer.time - start_time

class StructuredScene(SceneWithTimings):
    # Constants for font sizes, colors, and layout
    TITLE_FONT_SIZE = 44
    TEXT_FONT_SIZE = 34
    TEXT_COLOR = "#e7e8f2"
    BACKGROUND_COLOR = "#171923"

    def construct(self):
        self.camera.background_color = self.BACKGROUND_COLOR

    def clear_screen(self):
        self.play(FadeOut(*self.mobjects), run_time=0.5)
        self.wait(0.5)

    def substitute_symbols(self, text, symbols_mapping):
        for symbol, placeholder in symbols_mapping.items():
            text = text.replace(symbol, placeholder)
        return text

    def scene_visualization(self, title_text, text_content, diagram=None):
        title = MarkupText(title_text, gradient=(RED, YELLOW), font="Sans", font_size=self.TITLE_FONT_SIZE).to_edge(UP)
        self.play(FadeIn(title))
        self.wait(0.5)

        symbols_mapping = {
            r'\neq': '__NEQ__',
            r'\nabla': '__NABLA__',
            r'\natural': '__NATURAL__',
            r'\neg': '__NEG__',
            r'\nexists': '__NEXISTS__',
            r'\nleq': '__NLEQ__',
            r'\nleqslant': '__NLEQSLANT__',
            r'\nmid': '__NMID__',
            r'\nrightarrow': '__NRIGHTARROW__',
        }
        text_content = self.substitute_symbols(text_content, symbols_mapping)

        # Properly format the LaTeX content and ensure it doesn't cause errors
        formatted_text = text_content.replace(r'\n', r' \\').replace('\n', r' \\').replace(r'\\ \\', r'\\').replace(r'\\\\', r'\\').replace('  ', '')
        formatted_text = self.substitute_symbols(formatted_text, {v: k for k, v in symbols_mapping.items()})

        content = rf"\begin{{flushleft}} {formatted_text} \end{{flushleft}}"
        try:
            tex_text = Tex(content, color=self.TEXT_COLOR, font_size=self.TEXT_FONT_SIZE).next_to(title, DOWN)
            word_count = len(content.split())
        except ValueError:
            tex_text = MarkupText(text_content.replace(r'\\', '\n').replace('  ', ''), color=self.TEXT_COLOR, font_size=self.TEXT_FONT_SIZE, justify=True).scale(0.7).next_to(title, DOWN)
            word_count = len(text_content.split())

        with self.voiceover(text=text_content.replace('\\', '')) as tracker:
            # wait_time = tracker.duration
            self.play(Write(tex_text))

        if diagram:
            self.clear_screen()
            animation = getattr(self, diagram, None)
            if callable(animation):
                animation()

        self.wait(1)

    def run_scenes_sequentially(self, scenes_data):
        for scene in scenes_data:
            title = scene.get('title', '')
            text = scene.get('text', '')
            diagram = scene.get('diagram', None)
            self.scene_visualization(title, text, diagram)
            self.clear_screen()

class TopicAnimation(StructuredScene):
    def construct(self):
        # Change the scenes_data to match the topic, and provide LaTeX supported text only
        scenes_data = [
            {"title": "Introduction", "text": r'''Welcome to the topic of Arithmetic Progression (AP) and Geometric Progression (GP). In this session, we will dive into these two fundamental sequences in mathematics. Explore their definitions, properties, and applications in real-life scenarios. Let's get started!''', "diagram": None},
            {"title": "What is Arithmetic Progression?", "text": r'''An arithmetic progression is a sequence of numbers in which the difference between consecutive terms is constant. The sequence can be represented as:
            \[ a_n = a + (n-1)d \]
            where \( a \) is the first term and \( d \) is the common difference.''', "diagram": None},
            {"title": "Example of AP", "text": r'''Let's consider the Arithmetic Progression where the first term \( a = 2 \) and the common difference \( d = 3 \). The nth term can be calculated with:
            \[ a_n = 2 + (n-1) \cdot 3 \]
            So, the 5th term would be:
            \[ a_5 = 2 + (5-1) \cdot 3 = 14 \]''', "diagram": None},
            {"title": "What is Geometric Progression?", "text": r'''A geometric progression is a sequence of numbers where each term after the first is found by multiplying the previous one by a fixed, non-zero number called the common ratio \( r \). The sequence is given by:
            \[ a_n = ar^{(n-1)} \]
            where \( a \) is the first term and \( r \) is the common ratio.''', "diagram": None},
            {"title": "Example of GP", "text": r'''Let's consider the Geometric Progression where the first term \( a = 3 \) and the common ratio \( r = 2 \). The nth term can be calculated with:
            \[ a_n = 3 \cdot 2^{(n-1)} \]
            So, for the 4th term:
            \[ a_4 = 3 \cdot 2^{(4-1)} = 24 \]''', "diagram": None},
            {"title": "Comparison of AP and GP", "text": r'''In summary:
            - In AP, the difference between terms is constant (linear growth).
            - In GP, the ratio between terms is constant (exponential growth).
            Understanding these sequences is crucial for various applications in mathematics.''', "diagram": None},
            {"title": "Real-life Applications", "text": r'''Arithmetic and geometric progressions are commonly used in finance, engineering, and computer science:
            - AP is used in calculating loans and mortgages.
            - GP is essential in computations involving compound interest and population growth.''', "diagram": None},
            {"title": "Thank you!", "text": r'''Thank you for exploring Arithmetic and Geometric Progressions with us! We hope this lesson has enhanced your understanding. Keep practicing to master these concepts!''', "diagram": None},
            {"title": "Concluding Note", "text": r'''Understanding AP and GP is fundamental in higher mathematics. Continue to explore these sequences and their applications in depth. See you in the next lesson!''', "diagram": None},
            # The last scene will hold for five seconds.
        ]

        self.run_scenes_sequentially(scenes_data)

        # Write the total runtime to a file
        current_dir = os.path.dirname(os.path.realpath(__file__))
        python_file_name = os.path.basename(__file__)
        runtime_file_name = python_file_name.replace(".py", "_runtime.txt")
        full_path = os.path.join(current_dir, runtime_file_name)
        with open(full_path, "w") as f:
            f.write(f"{self.total_runtime}\n")

# To run this code, save it to a file named `scene.py` and run the following command in your terminal:
# manim -pql --disable_caching --flush_cache --no_latex_cleanup scene.py TopicAnimation
```

</details>

## Logs
<details><summary>Terminal output</summary>

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /var/www/html/manim/venv/lib/python3.12/site-packages/manim/cli/render/commands.py:120 in     │
│ render                                                                                           │
│                                                                                                  │
│   117 │   │   │   try:                                                                           │
│   118 │   │   │   │   with tempconfig({}):                                                       │
│   119 │   │   │   │   │   scene = SceneClass()                                                   │
│ ❱ 120 │   │   │   │   │   scene.render()                                                         │
│   121 │   │   │   except Exception:                                                              │
│   122 │   │   │   │   error_console.print_exception()                                            │
│   123 │   │   │   │   sys.exit(1)                                                                │
│                                                                                                  │
│ /var/www/html/manim/venv/lib/python3.12/site-packages/manim/scene/scene.py:229 in render      │
│                                                                                                  │
│    226 │   │   """                                                                               │
│    227 │   │   self.setup()                                                                      │
│    228 │   │   try:                                                                              │
│ ❱  229 │   │   │   self.construct()                                                              │
│    230 │   │   except EndSceneEarlyException:                                                    │
│    231 │   │   │   pass                                                                          │
│    232 │   │   except RerunSceneException as e:                                                  │
│                                                                                                  │
│ /var/www/html/manim/ap_gp_explanation.py:143 in construct                                        │
│                                                                                                  │
│   140 │   │   │   # The last scene will hold for five seconds.                                   │
│   141 │   │   ]                                                                                  │
│   142 │   │                                                                                      │
│ ❱ 143 │   │   self.run_scenes_sequentially(scenes_data)                                          │
│   144 │   │                                                                                      │
│   145 │   │   # Write the total runtime to a file                                                │
│   146 │   │   current_dir = os.path.dirname(os.path.realpath(__file__))                          │
│                                                                                                  │
│ /var/www/html/manim/ap_gp_explanation.py:109 in run_scenes_sequentially                          │
│                                                                                                  │
│   106 │   │   │   title = scene.get('title', '')                                                 │
│   107 │   │   │   text = scene.get('text', '')                                                   │
│   108 │   │   │   diagram = scene.get('diagram', None)                                           │
│ ❱ 109 │   │   │   self.scene_visualization(title, text, diagram)                                 │
│   110 │   │   │   self.clear_screen()                                                            │
│   111                                                                                            │
│   112 class TopicAnimation(StructuredScene):                                                     │
│                                                                                                  │
│ /var/www/html/manim/ap_gp_explanation.py:88 in scene_visualization                               │
│                                                                                                  │
│    85 │   │   │   tex_text = MarkupText(text_content.replace(r'\\', '\n').replace('  ', ''), c   │
│    86 │   │   │   word_count = len(text_content.split())                                         │
│    87 │   │                                                                                      │
│ ❱  88 │   │   with self.voiceover(text=text_content.replace('\\', '').replace('\n', ' ')) as t   │
│    89 │   │   │   # wait_time = tracker.duration                                                 │
│    90 │   │   │   self.play(Write(tex_text))                                                     │
│    91                                                                                            │
│                                                                                                  │
│ /usr/lib/python3.12/contextlib.py:137 in __enter__                                               │
│                                                                                                  │
│   134 │   │   # they are only needed for recreation, which is not possible anymore               │
│   135 │   │   del self.args, self.kwds, self.func                                                │
│   136 │   │   try:                                                                               │
│ ❱ 137 │   │   │   return next(self.gen)                                                          │
│   138 │   │   except StopIteration:                                                              │
│   139 │   │   │   raise RuntimeError("generator didn't yield") from None                         │
│   140                                                                                            │
│                                                                                                  │
│ /var/www/html/manim/venv/lib/python3.12/site-packages/manim_voiceover/voiceover_scene.py:186  │
│ in voiceover                                                                                     │
│                                                                                                  │
│   183 │   │                                                                                      │
│   184 │   │   try:                                                                               │
│   185 │   │   │   if text is not None:                                                           │
│ ❱ 186 │   │   │   │   yield self.add_voiceover_text(text, **kwargs)                              │
│   187 │   │   │   elif ssml is not None:                                                         │
│   188 │   │   │   │   yield self.add_voiceover_ssml(ssml, **kwargs)                              │
│   189 │   │   finally:                                                                           │
│                                                                                                  │
│ /var/www/html/manim/venv/lib/python3.12/site-packages/manim_voiceover/voiceover_scene.py:69   │
│ in add_voiceover_text                                                                            │
│                                                                                                  │
│    66 │   │   │   │   "You need to call init_voiceover() before adding a voiceover."             │
│    67 │   │   │   )                                                                              │
│    68 │   │                                                                                      │
│ ❱  69 │   │   dict_ = self.speech_service._wrap_generate_from_text(text, **kwargs)               │
│    70 │   │   tracker = VoiceoverTracker(self, dict_, self.speech_service.cache_dir)             │
│    71 │   │   self.add_sound(str(Path(self.speech_service.cache_dir) / dict_["final_audio"]))    │
│    72 │   │   self.current_tracker = tracker                                                     │
│                                                                                                  │
│ /var/www/html/manim/venv/lib/python3.12/site-packages/manim_voiceover/services/base.py:98 in  │
│ _wrap_generate_from_text                                                                         │
│                                                                                                  │
│    95 │   │   │   transcription_result = self._whisper_model.transcribe(                         │
│    96 │   │   │   │   str(Path(self.cache_dir) / original_audio), **self.transcription_kwargs    │
│    97 │   │   │   )                                                                              │
│ ❱  98 │   │   │   logger.info("Transcription: " + transcription_result.text)                     │
│    99 │   │   │   word_boundaries = timestamps_to_word_boundaries(                               │
│   100 │   │   │   │   transcription_result.segments_to_dicts()                                   │
│   101 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'dict' object has no attribute 'text'
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS: Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-1012-aws x86_64) EC2 AWS
- RAM: 4 GB
  - Python version: Python 3.12.3
- Installed modules:
```
Package                                 Version
--------------------------------------- ---------------
adrf                                    0.1.7
aioboto3                                13.1.1
aiobotocore                             2.13.1
aiofiles                                24.1.0
aiohappyeyeballs                        2.4.0
aiohttp                                 3.10.6
aioitertools                            0.12.0
aiosignal                               1.3.1
altgraph                                0.17.4
amqp                                    5.2.0
annotated-types                         0.7.0
anyio                                   4.6.0
asgiref                                 3.8.1
astroid                                 3.3.5
async-property                          0.2.2
attrs                                   24.2.0
autobahn                                24.4.2
Automat                                 24.8.1
azure-cognitiveservices-speech          1.40.0
azure-core                              1.31.0
azure-identity                          1.18.0
beautifulsoup4                          4.12.3
billiard                                4.2.1
boto3                                   1.34.131
botocore                                1.34.131
CacheControl                            0.14.0
cachetools                              5.5.0
celery                                  5.4.0
certifi                                 2024.8.30
cffi                                    1.17.1
channels                                4.1.0
channels-redis                          4.2.0
charset-normalizer                      3.3.2
click                                   8.1.7
click-didyoumean                        0.3.1
click-plugins                           1.1.1
click-repl                              0.3.0
cloup                                   3.0.5
cohere                                  5.10.0
colorlog                                6.8.2
constantly                              23.10.4
cryptography                            43.0.1
daphne                                  4.1.2
dataclasses-json                        0.6.7
datasets                                3.0.1
decorator                               4.4.2
deepl                                   1.19.1
Deprecated                              1.2.14
dill                                    0.3.8
dirtyjson                               1.0.8
distro                                  1.9.0
Django                                  4.2.7
django-celery-results                   2.5.1
django-cors-headers                     4.4.0
django-crontab                          0.7.1
django-redis                            5.4.0
django-storages                         1.14.4
djangorestframework                     3.15.2
environs                                11.0.0
eval_type_backport                      0.2.0
evdev                                   1.7.1
fastapi                                 0.115.0
fastavro                                1.9.7
ffmpeg                                  1.4
ffmpeg-downloader                       0.3.0
ffmpeg-python                           0.2.0
filelock                                3.16.1
firebase-admin                          6.5.0
frozenlist                              1.4.1
fsspec                                  2024.6.1
future                                  1.0.0
glcontext                               3.0.0
google-api-core                         2.20.0
google-api-python-client                2.147.0
google-auth                             2.35.0
google-auth-httplib2                    0.2.0
google-cloud-core                       2.4.1
google-cloud-firestore                  2.19.0
google-cloud-storage                    2.18.2
google-crc32c                           1.6.0
google-resumable-media                  2.7.2
googleapis-common-protos                1.65.0
greenlet                                3.1.1
grpcio                                  1.66.1
grpcio-status                           1.66.1
gTTS                                    2.5.3
gunicorn                                23.0.0
h11                                     0.14.0
httpcore                                1.0.5
httplib2                                0.22.0
httptools                               0.6.1
httpx                                   0.27.2
httpx-sse                               0.4.0
huggingface-hub                         0.25.1
humanhash3                              0.0.6
hyperlink                               21.0.0
idna                                    3.10
imageio                                 2.35.1
imageio-ffmpeg                          0.5.1
incremental                             24.7.2
isort                                   5.13.2
isosurfaces                             0.1.2
Jinja2                                  3.1.4
jiter                                   0.5.0
jmespath                                1.0.1
joblib                                  1.4.2
jsonpath-python                         1.0.6
kombu                                   5.4.2
llama-cloud                             0.1.0
llama-index                             0.11.13
llama-index-agent-openai                0.3.4
llama-index-cli                         0.3.1
llama-index-core                        0.11.13.post1
llama-index-embeddings-adapter          0.2.2
llama-index-embeddings-huggingface      0.3.1
llama-index-embeddings-openai           0.2.5
llama-index-finetuning                  0.2.1
llama-index-indices-managed-llama-cloud 0.4.0
llama-index-legacy                      0.9.48.post3
llama-index-llms-azure-openai           0.2.1
llama-index-llms-mistralai              0.2.5
llama-index-llms-ollama                 0.3.2
llama-index-llms-openai                 0.2.9
llama-index-multi-modal-llms-openai     0.2.1
llama-index-postprocessor-cohere-rerank 0.2.1
llama-index-program-openai              0.2.0
llama-index-question-gen-openai         0.2.0
llama-index-readers-file                0.2.2
llama-index-readers-llama-parse         0.3.0
llama-parse                             0.5.6
manim                                   0.18.1
manim-voiceover                         0.3.6
ManimPango                              0.6.0
mapbox_earcut                           1.0.2
markdown-it-py                          3.0.0
MarkupSafe                              2.1.5
marshmallow                             3.22.0
mccabe                                  0.7.0
mdurl                                   0.1.2
minijinja                               2.2.0
mistralai                               1.1.0
moderngl                                5.11.1
moderngl-window                         2.4.6
more-itertools                          10.5.0
moviepy                                 1.0.3
mpmath                                  1.3.0
msal                                    1.31.0
msal-extensions                         1.2.0
msgpack                                 1.1.0
multidict                               6.1.0
multipledispatch                        1.0.0
multiprocess                            0.70.16
mutagen                                 1.47.0
mypy-extensions                         1.0.0
mysqlclient                             2.2.4
nest-asyncio                            1.6.0
networkx                                3.3
nltk                                    3.9.1
numpy                                   1.26.4
nvidia-cublas-cu12                      12.1.3.1
nvidia-cuda-cupti-cu12                  12.1.105
nvidia-cuda-nvrtc-cu12                  12.1.105
nvidia-cuda-runtime-cu12                12.1.105
nvidia-cudnn-cu12                       9.1.0.70
nvidia-cufft-cu12                       11.0.2.54
nvidia-curand-cu12                      10.3.2.106
nvidia-cusolver-cu12                    11.4.5.107
nvidia-cusparse-cu12                    12.1.0.106
nvidia-nccl-cu12                        2.20.5
nvidia-nvjitlink-cu12                   12.6.68
nvidia-nvtx-cu12                        12.1.105
ollama                                  0.3.3
openai                                  1.46.0
openai-whisper                          20230117
packaging                               24.1
pandas                                  2.2.3
parameterized                           0.9.0
pillow                                  10.4.0
pip                                     24.2
platformdirs                            4.3.6
playsound                               1.3.0
portalocker                             2.10.1
proglog                                 0.1.10
prompt_toolkit                          3.0.48
proto-plus                              1.24.0
protobuf                                5.28.2
pyarrow                                 17.0.0
pyasn1                                  0.6.1
pyasn1_modules                          0.4.1
PyAudio                                 0.2.14
pycairo                                 1.27.0
pycparser                               2.22
pydantic                                2.9.2
pydantic_core                           2.23.4
pydub                                   0.25.1
pyglet                                  2.0.17
Pygments                                2.18.0
pyinstaller                             6.10.0
pyinstaller-hooks-contrib               2024.8
PyJWT                                   2.9.0
pylint                                  3.3.1
pynput                                  1.7.7
pyOpenSSL                               24.2.1
pyotp                                   2.9.0
pyparsing                               3.1.4
pypdf                                   4.3.1
PyPDF2                                  3.0.1
pyrr                                    0.10.3
python-dateutil                         2.8.2
python-dotenv                           0.21.1
python-multipart                        0.0.12
python-slugify                          8.0.4
python-xlib                             0.33
pyttsx3                                 2.98
pytz                                    2024.2
PyYAML                                  6.0.2
redis                                   5.0.8
regex                                   2024.9.11
requests                                2.32.3
rich                                    13.8.1
rsa                                     4.9
s3transfer                              0.10.2
safetensors                             0.4.5
scikit-learn                            1.5.2
scipy                                   1.14.1
screeninfo                              0.8.1
sentence-transformers                   3.1.1
service-identity                        24.1.0
setuptools                              59.8.0
six                                     1.16.0
skia-pathops                            0.8.0.post1
sniffio                                 1.3.1
soupsieve                               2.6
sox                                     1.5.0
SQLAlchemy                              2.0.35
sqlparse                                0.5.1
srt                                     3.5.3
stable-ts                               1.1.0
starlette                               0.38.6
striprtf                                0.0.26
svgelements                             1.9.6
sympy                                   1.13.3
tenacity                                8.5.0
text-unidecode                          1.3
threadpoolctl                           3.5.0
tiktoken                                0.7.0
tokenizers                              0.20.0
tomlkit                                 0.13.2
torch                                   2.4.1
torchaudio                              2.4.1
tqdm                                    4.66.5
transformers                            4.45.0
triton                                  3.0.0
Twisted                                 24.7.0
txaio                                   23.1.1
types-requests                          2.32.0.20240914
typing_extensions                       4.12.2
typing-inspect                          0.9.0
tzdata                                  2024.2
uritemplate                             4.1.1
urllib3                                 2.2.3
uvicorn                                 0.30.6
uvloop                                  0.20.0
vine                                    5.1.0
watchdog                                5.0.2
watchfiles                              0.24.0
wcwidth                                 0.2.13
websockets                              13.1
wheel                                   0.44.0
wrapt                                   1.16.0
xxhash                                  3.5.0
yarl                                    1.12.1
zope.interface                          7.0.3
```
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020): Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian)
+ Installed LaTeX packages: texlive texlive-latex-extra texlive-fonts-recommended texlive-full

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13 (Ubuntu 13.2.0-23ubuntu3)
configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --disable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libjack --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-pocketsphinx --enable-librsvg --enable-libjxl --enable-shared
libavutil      58. 29.100 / 58. 29.100
libavcodec     60. 31.102 / 60. 31.102
libavformat    60. 16.100 / 60. 16.100
libavdevice    60.  3.100 / 60.  3.100
libavfilter     9. 12.100 /  9. 12.100
libswscale      7.  5.100 /  7.  5.100
libswresample   4. 12.100 /  4. 12.100
libpostproc    57.  3.100 / 57.  3.100
```
</details>

**Comment by dasayan05** [comment]
sorry, I am facing the same issue. this issue was closed without mentioning how it was solved. can you provide some details, @osolmaz @mayankwebbing ?

**Comment by mayankwebbing** [comment]
It is recommended to use `Python 3.10` for using `manim_voiceover`.

Can you kindly provide the Python version are you using?

PS: Switching to Python 3.10 will solve your maximum problems, just reinstall the dependency as per your requirements.

**Comment by dasayan05** [comment]
I am using Py3.10 though.

**Comment by dasayan05** [comment]
I think this is something related to the transcription model. As I don't need transcription at the moment, turning it off (i.e. `OpenAIService(..., transcription_model=None)` makes the error go away.

**Comment by mayankwebbing** [comment]
May be yes, In my case that wasn't the cause of error.
